POST https://sp-taskify-api.vercel.app/docs/13-4/auth/login
Content-Type: application/json

{
    "id": 5290,
    "email": "mgmgmg@gmail.com",
    "password": "asdf1234",
    "nickname": "밈밈",
    "profileImageUrl": null,
    "createdAt": "2025-03-21T17:24:57.201Z",
    "updatedAt": "2025-03-21T17:24:57.201Z"
}