import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/containers/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        pretendard: ["Pretendard"],
      },
      fontSize: {
        "3xl-Bold": ["32px", { lineHeight: "42px", fontWeight: "700" }],
        "3xl-Semibold": ["32px", { lineHeight: "42px", fontWeight: "600" }],
        "2xl-Bold": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "2xl-Semibold": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "2xl-Medium": ["24px", { lineHeight: "32px", fontWeight: "500" }],
        "2xl-Regular": ["24px", { lineHeight: "32px", fontWeight: "400" }],
        "xl-Bold": ["20px", { lineHeight: "32px", fontWeight: "700" }],
        "xl-Semibold": ["20px", { lineHeight: "32px", fontWeight: "600" }],
        "xl-Medium": ["20px", { lineHeight: "32px", fontWeight: "500" }],
        "xl-Regular": ["20px", { lineHeight: "32px", fontWeight: "400" }],
        "2lg-Bold": ["18px", { lineHeight: "26px", fontWeight: "700" }],
        "2lg-Semibold": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "2lg-Medium": ["18px", { lineHeight: "26px", fontWeight: "500" }],
        "2lg-Regular": ["18px", { lineHeight: "26px", fontWeight: "400" }],
        "lg-Bold": ["16px", { lineHeight: "26px", fontWeight: "700" }],
        "lg-Semibold": ["16px", { lineHeight: "26px", fontWeight: "600" }],
        "lg-Medium": ["16px", { lineHeight: "26px", fontWeight: "500" }],
        "lg-Regular": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "md-Bold": ["14px", { lineHeight: "24px", fontWeight: "700" }],
        "md-Semibold": ["14px", { lineHeight: "24px", fontWeight: "600" }],
        "md-Medium": ["14px", { lineHeight: "24px", fontWeight: "500" }],
        "md-Regular": ["14px", { lineHeight: "24px", fontWeight: "400" }],
        "sm-Semibold": ["13px", { lineHeight: "22px", fontWeight: "600" }],
        "sm-Medium": ["13px", { lineHeight: "22px", fontWeight: "500" }],
        "xs-Semibold": ["12px", { lineHeight: "20px", fontWeight: "600" }],
        "xs-Medium": ["12px", { lineHeight: "18px", fontWeight: "500" }],
        "xs-Regular": ["12px", { lineHeight: "18px", fontWeight: "400" }],
      },
      colors: {
        primary: "#5534DA",
        secondary: "F1EFFD",
        red: "#D6173A",
        green: "#7AC555",
        purple: "#760DDF",
        orange: "#FFA500",
        blue: "#76A5EA",
        pink: "#E876EA",
        wihte: "#FFFFFF",
        black: {
          1000: "#000000",
          900: "#171717",
          800: "#333236",
          700: "4B4B4B",
        },
        glay: {
          1000: "#787486",
          900: "#9FA6B2",
          800: "#D9D9D9",
          700: "#EEEEEE",
          600: "#FAFAFA",
        },
      },
    },
  },
  plugins: [],
} satisfies Config;
